Fixed some issues.

diff --git a/.github/workflows/waydroid.yml b/.github/workflows/waydroid.yml
--- a/.github/workflows/waydroid.yml
+++ b/.github/workflows/waydroid.yml
@@ -157,6 +157,7 @@ jobs:
           fi
 
       - name: Repo Build
+        shell: bash
         run: |
           export TERM=xterm-256color
 
@@ -169,11 +170,87 @@ jobs:
           # Repo Process
           repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
           repo sync build/make -j$(nproc --all)
-          wget https://raw.githubusercontent.com/JackA1ltman/Waydroid_Auto_Build/refs/heads/main/generate-manifest.sh -O $GITHUB_WORKSPACE/generate-manifests.sh
-          chmod 777 $GITHUB_WORKSPACE/generate-manifests.sh
-          pwd
-          ls -al ./
-          timeout 15s bash "$GITHUB_WORKSPACE/generate-manifests.sh"
+
+          # Generate
+          top_dir=`pwd`
+          LOCALDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+          loc_man="${top_dir}/.repo/local_manifests"
+          manifests_url="https://raw.githubusercontent.com/waydroid/android_vendor_waydroid/lineage-20/manifest_scripts/manifests"
+          manifests_path="${LOCALDIR}/manifests"
+
+          red=`tput setaf 1`
+          green=`tput setaf 2`
+          yellow=`tput setaf 3`
+          blue=`tput setaf 4`
+          purple=`tput setaf 5`
+          teal=`tput setaf 6`
+          light=`tput setaf 7`
+          dark=`tput setaf 8`
+          ltred=`tput setaf 9`
+          ltgreen=`tput setaf 10`
+          ltyellow=`tput setaf 11`
+          ltblue=`tput setaf 12`
+          ltpurple=`tput setaf 13`
+          CL_CYN=`tput setaf 12`
+          CL_RST=`tput sgr0`
+          reset=`tput sgr0`
+
+          if [ ! -d "${top_dir}/.repo" ]; then
+            echo -e ${reset}""${reset}
+            echo -e ${ltred}"ERROR: Manifest generation requires repo to be initialized first."${reset}
+            echo -e ${reset}""${reset}
+            exit
+          fi
+
+          if [ ! -f build/make/core/version_defaults.mk ]; then
+            echo -e ${reset}""${reset}
+            echo -e ${ltred}"ERROR: Missing build/make. Please run `repo sync build/make` first."${reset}
+            echo -e ${reset}""${reset}
+            exit
+          fi
+
+          sdkv=$(cat build/make/core/version_defaults.mk | grep "PLATFORM_SDK_VERSION :=" | grep -o "[[:digit:]]\+")
+          manifests_url="${manifests_url}-${sdkv}"
+          manifests_path="${manifests_path}-${sdkv}"
+
+          mkdir -p ${loc_man}
+
+          echo -e ${reset}""${reset}
+          echo -e ${green}"Placing manifest fragments..."${reset}
+          echo -e ${reset}""${reset}
+          if [ -d "${manifests_path}" ]; then
+            cp -fpr ${manifests_path}/*.xml "${loc_man}/"
+          else
+            echo -e ${reset}""${reset}
+            echo -e ${ltblue}"INFO: Manifests not found, downloading"${reset}
+            echo -e ${reset}""${reset}
+            wget "${manifests_url}/00-remotes.xml" -O "${loc_man}/00-remotes.xml"
+            wget "${manifests_url}/01-removes.xml" -O "${loc_man}/01-removes.xml"
+            wget "${manifests_url}/02-waydroid.xml" -O "${loc_man}/02-waydroid.xml"
+          fi
+
+          echo -e ${reset}""${reset}
+          echo -e ${teal}"INFO: Cleaning up remove manifest entries"${reset}
+          echo -e ${reset}""${reset}
+          while IFS= read -r rpitem; do
+            if [[ $rpitem == *"remove-project"* ]]; then
+                rpitem_trimmed="$(echo "$rpitem" | xargs)"
+                if grep -qRlZ "$rpitem_trimmed" "${top_dir}/.repo/manifests/"; then
+                    echo -e ${yellow}"WARN: ROM already includes: $rpitem"${reset}
+                else
+                    echo -e ${green}"INFO: Needed: $rpitem"${reset}
+                    prefix="<remove-project name="
+                    suffix=" />"
+                    item=${rpitem_trimmed#"$prefix"}
+                    item=${item%"$suffix"}
+                    if ! grep -qRlZ "$item" "${top_dir}/.repo/manifests/"; then
+                        sed -e "$item"'d' "${loc_man}/01-removes.xml"
+                    fi
+                fi
+            fi
+          done < "${loc_man}/01-removes.xml"
+
+          # Build
           repo sync -j$(nproc --all)
           . build/envsetup.sh
           apply-waydroid-patches
